### ISSUE TITLE
Publish package

### ISSUE THREAD

**Issue by m301** [Langenfeld/py-gitea#2]
I think you should publish this repository as a package for wider adoption and easy use. I want to use this repo as package, it's maintained in a better manner. 

Let me know if I can contribute.

**Comment by Langenfeld** [comment]
Ok, yes, this might be sensible although there is so much untested and unimplemented stuff :). There now is a package https://pypi.org/project/py-gitea/.

Sure, any contribution is apreciated.

**Comment by m301** [comment]
You already did that :)

I was asking to contribute on that front only.  Next time I will raise a PR.
