### ISSUE TITLE
Code Formatting

### ISSUE THREAD

**Issue by shrik450** [Langenfeld/py-gitea#23]
Hey! I want to upstream some of the changes we're making to py-allspice, which we forked from py-gitea. I'm wondering if we can set up an automated formatter for this repo, preferably black, as I think that would make getting consistent formatting across many contributors easier.

**Comment by Langenfeld** [comment]
Hey, (and also sorry for the long absence), yes, merging some of your changes would be really nice. I would agree, that we should use black in order to keep diffs readable. Regarding automatic formatting, I have to look into into actions. (also sorry for the long absence)
