### ISSUE TITLE
Auto-generate typed attributes for API Objects

### ISSUE THREAD

**Issue by shrik450** [Langenfeld/py-gitea#29]
Hey! Over in py-allspice, we recently added [a script](https://github.com/AllSpiceIO/py-allspice/blob/main/scripts/generate_attribute_types.py) that uses `sys.setprofile` to identify the attributes in API objects and their types. This is really useful information when working with the client, as you often have to use a REPL and `dir()` to actually know what information is available in each object. I can upstream this work to py-gitea as well if you are interested.

I should note that there are a couple of reasons you might *not* want to do this:

- In py-allspice, we have a different versioning policy: we only support the latest version of AllSpice Hub. This may not be true for all users of py-gitea, so the attributes that you generate might not be valid for those who are on older versions of gitea.
- If you do set up type signatures, it is important to ensure that they're not getting out of date, so you'd also need to set up a CI pipeline which would check this on a regular basis. We do this in py-allspice, but py-gitea doesn't have CI right now. If you don't want to set up CI, the previous issue can be compounded by out of date types.

**Comment by Langenfeld** [comment]
Hello shrik450,
I looked into the annotated version fo the api objects in your repository and this is really nice. Yes, the common approach we use is having the gitea api documentation open when working with gitea - but yes, thats not the most convenient way to work. Regarding upstreaming the script, I would like to take some time to look at the results in detail.

**Comment by milahu** [comment]
codegen - isnt that a solved problem?

https://docs.gitea.com/api/1.22/ says

> Download OpenAPI specification: https://docs.gitea.com/redocusaurus/plugin-redoc-1.yaml

[openapi-python-client](https://github.com/openapi-generators/openapi-python-client) fails to read that yaml file

<details>

```
$ openapi-python-client generate --url https://docs.gitea.com/redocusaurus/plugin-redoc-1.yaml
Error(s) encountered while generating, client was not created

Failed to parse OpenAPI document

You may be trying to use a Swagger document; this is not supported by this project.

215 validation errors for OpenAPI
paths./admin/hooks.post.parameters.0.Parameter.in
  Input should be 'query', 'path', 'header' or 'cookie' [type=enum, input_value='body', input_type=str]
paths./admin/hooks.post.parameters.0.Reference.$ref
  Field required [type=missing, input_value={'name': 'body', 'in': 'b...ions/CreateHookOption'}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
paths./admin/hooks/{id}.patch.parameters.1.Parameter.in
  Input should be 'query', 'path', 'header' or 'cookie' [type=enum, input_value='body', input_type=str]
...
```

</details>

but it works with [swagger-codegen](https://github.com/swagger-api/swagger-codegen)

```
swagger-codegen generate \
  -i https://docs.gitea.com/redocusaurus/plugin-redoc-1.yaml \
  -l python \
  -o gitea-client-python \
  -DpackageName=gitea_client
```

result: [gitea-client-python](https://github.com/milahu/gitea-client-python)

see also https://github.com/go-gitea/gitea/issues/31714

**Comment by shrik450** [comment]
There's already a few other packages on pypi that use OpenAPI generator: https://pypi.org/project/py-gitea-opensuse-org/

But the quality of the generated API client is debatable, and I (and I believe many others) vastly prefer py-gitea's API.

**Comment by Langenfeld** [comment]
@shrik450 hey, again thank you for the offer to upstream the script. Hardcoding the repository units yesterday I realised, that i'd rather stay with the completely input driven approach as it keeps this library kind of robust.
